AWSTemplateFormatVersion: 2010-09-09
Description: Start an OpenVPN server

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
  InstanceImageId:
    Type: AWS::EC2::Image::Id
  MainVPCImportId:
    Type: String
    Default: network-MainVPCId
  PublicSubnetImportId:
    Type: String
    Default: network-PublicSubnetId
  CACertificate:
    Type: String
  ServerCertificate:
    Type: String
  ServerPrivateKey:
    Type: String
    NoEcho: true

Resources:
  OpenVPNSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh and openvpn ports
      VpcId:
        Fn::ImportValue: !Ref MainVPCImportId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: udp
        FromPort: 1194
        ToPort: 1194
        CidrIp: 0.0.0.0/0
  OpenVPNServer:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        setupCfnHup:
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackName}
                region=${AWS::Region}
                interval=1
                verbose=true
              mode: "000400"
              owner: root
              group: root
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.OpenVPNServer.Metadata
                action=/usr/local/bin/cfn-init -v --configsets update --stack ${AWS::StackName} --resource OpenVPNServer --region ${AWS::Region}
                runas=root
              mode: "000400"
              owner: root
              group: root
            /etc/systemd/system/cfn-hup.service:
              content: !Sub |
                [Unit]
                Description=Cfn-hup daemon
                [Service]
                ExecStart=/usr/local/bin/cfn-hup -v
                [Install]
                WantedBy=multi-user.target
              mode: "000600"
              owner: root
              group: root
          commands:
            enableService:
              command: systemctl enable cfn-hup
            restartService:
              command: systemctl start cfn-hup
        setupServer:
          packages:
            apt:
              openvpn: ["2.4.7-1"]
              openssl: []
              iptables-persistent: []
          files:
            /etc/openvpn/server/server.pem:
              content: !Ref ServerPrivateKey
              mode: "000600"
              owner: root
              group: root
            /etc/openvpn/server/server.crt:
              content: !Ref ServerCertificate
              mode: "000644"
              owner: root
              group: root
            /etc/openvpn/server/ca.crt:
              content: !Ref CACertificate
              mode: "000644"
              owner: root
              group: root
            /etc/openvpn/server/servertcp.conf:
              content: |
                server 10.8.0.0 255.255.255.0
                proto udp
                dev tun
                keepalive 30 60
                remote-cert-tls client
                cipher AES-256-CBC
                ca ca.crt
                dh dh.pem
                cert server.crt
                key server.pem
                push "redirect-gateway def1"
              mode: "000644"
              owner: root
              group: root
          commands:
            generateDHparams:
              command: openssl dhparam -out /etc/openvpn/server/dh.pem 2048
            natClientTraffic:
              command: iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
            saveRules:
              command: iptables-save > /etc/iptables/rules.v4
            enableIpv4Forwarding:
              command: sysctl -w net.ipv4.ip_forward=1
            changeIpv4ForwardingConfig:
              command: sed -i 's/#net\.ipv4\.ip_forward.*/net.ipv4.ip_forward=1/' /etc/sysctl.conf
        startServer:
          commands:
            enableService:
              command: systemctl enable openvpn-server@servertcp
            startService:
              command: systemctl start openvpn-server@servertcp
        restartServer:
          commands:
            daemonReload:
              command: systemctl daemon-reload
            restartService:
              command: systemctl restart openvpn-server@servertcp
        configSets:
          default:
          - setupCfnHup
          - setupServer
          - startServer
          update:
          - setupServer
          - restartServer
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref InstanceImageId
      SubnetId:
        Fn::ImportValue: !Ref PublicSubnetImportId
      SecurityGroupIds:
      - !Ref OpenVPNSecurityGroup
      KeyName: !Ref KeyName
      Tags:
      - Key: Name
        Value: openvpn
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            apt-get update
            apt-get install -y python-pip
            pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
            cfn-init -v --stack ${AWS::StackName} --resource OpenVPNServer --region ${AWS::Region}

Outputs:
  OpenVPNServerPublicIp:
    Value: !GetAtt OpenVPNServer.PublicIp